import nike_data as nd
import json,codecs,os

nikeData = [
    {
        "homme":    [{
          "chaussures":nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/homme-lifestyle-chaussures/7puZoneZoi3',"Lifestyle")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/homme-running-chaussures/7puZ8yzZoi3',"Running")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/homme-football-chaussures/7puZ896Zoi3',"Football")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/homme-basketball-chaussures/7puZ8r1Zoi3',"Basketball")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/homme-fitness-training-chaussures/7puZ9hkZoi3',"Fitness et training")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/homme-skateboard-chaussures/7puZ9yqZoi3',"Skateboard ")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/homme-tennis-chaussures/7puZ8r0Zoi3',"Tennis ")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/homme-golf-chaussures/7puZahaZoi3',"Golf")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/homme-football-am%C3%A9ricain-chaussures/7puZbgcZoi3',"Football Américain")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/homme-baseball-chaussures/7puZbumZoi3',"Baseball")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/homme-athl%C3%A9tisme-chaussures/7puZ9yoZoi3',"Athlétisme")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/homme-rugby-chaussures/7puZbstZoi3',"Rugby")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/homme-marche-chaussures/7puZ9ypZoi3',"Marche")
        }],

        "femme":    [{
          "chaussures":nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/femme-lifestyle-chaussures/7ptZoneZoi3',"Lifestyle")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/femme-running-chaussures/7ptZ8yzZoi3',"Running")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/femme-football-chaussures/7ptZ896Zoi3',"Football")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/femme-basketball-chaussures/7ptZ8r1Zoi3',"Basketball")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/femme-fitness-training-chaussures/7ptZ9hkZoi3',"Fitness et training")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/femme-skateboard-chaussures/7ptZ9yqZoi3',"Skateboard ")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/femme-tennis-chaussures/7ptZ8r0Zoi3',"Tennis ")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/femme-golf-chaussures/7ptZahaZoi3',"Golf")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/femme-football-am%C3%A9ricain-chaussures/7ptZbgcZoi3',"Football Américain")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/femme-baseball-chaussures/7ptZbumZoi3',"Baseball")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/femme-athl%C3%A9tisme-chaussures/7ptZ9yoZoi3',"Athlétisme")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/femme-rugby-chaussures/7ptZbstZoi3',"Rugby")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/femme-marche-chaussures/7ptZ9ypZoi3',"Marche")
        }],
        "garcon":   [{
          "chaussures":nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/gar%C3%A7on-lifestyle-chaussures/7pvZoneZoi3',"Lifestyle")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/gar%C3%A7on-running-chaussures/7pvZ8yzZoi3',"Running")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/gar%C3%A7on-football-chaussures/7pvZ896Zoi3',"Football")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/gar%C3%A7on-basketball-chaussures/7pvZ8r1Zoi3',"Basketball")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/gar%C3%A7on-fitness-training-chaussures/7pvZ9hkZoi3',"Fitness et training")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/gar%C3%A7on-skateboard-chaussures/7pvZ9yqZoi3',"Skateboard ")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/gar%C3%A7on-tennis-chaussures/7pvZ8r0Zoi3',"Tennis ")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/gar%C3%A7on-golf-chaussures/7pvZahaZoi3',"Golf")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/gar%C3%A7on-rugby-chaussures/7pvZbstZoi3',"Rugby")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/gar%C3%A7on-danse-chaussures/7pvZ8ieZoi3',"Danse")
        }],
        "fille":    [{
          "chaussures":nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/fille-lifestyle-chaussures/7pwZoneZoi3',"Lifestyle")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/fille-running-chaussures/7pwZ8yzZoi3',"Running")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/fille-football-chaussures/7pwZ896Zoi3',"Football")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/fille-basketball-chaussures/7pwZ8r1Zoi3',"Basketball")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/fille-fitness-training-chaussures/7pwZ9hkZoi3',"Fitness et training")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/fille-skateboard-chaussures/7pwZ9yqZoi3',"Skateboard ")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/fille-tennis-chaussures/7pwZ8r0Zoi3',"Tennis ")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/fille-golf-chaussures/7pwZahaZoi3',"Golf")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/fille-rugby-chaussures/7pwZbstZoi3',"Rugby")+nd.getNikeData('https://store.nike.com/fr/fr_fr/pw/fille-danse-chaussures/7pwZ8ieZoi3',"Danse")
        }]
    }
]
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)),'database.json'), 'w',encoding= "utf-8") as f:
  json.dump(nikeData, f, ensure_ascii=True)
